### ISSUE TITLE
容器启动和停止比较慢

### ISSUE THREAD

**Issue by tangniyuqi** [mingfunwong/docker-bt#1]
感谢你的贡献，今天使用发现一个问题，启动和停止容器比较慢，而且严重是造成系统卡顿
不知道是怎么原因呢
https://github.com/jae-jae/docker-baota 这个镜像似乎没有这个问题 ，启动/停止容器也很快

**Comment by AkiraTach** [comment]
如果运行环境是 Windows / OS X ，因为虚拟机端口映射比较慢，需要把 -p 39000-40000:39000-40000 改成 -p 39000-39050:39000-39050 。

**Comment by tangniyuqi** [comment]
是centos7

**Comment by tangniyuqi** [comment]
![_20180420182049](https://user-images.githubusercontent.com/5830538/39046160-cfaa0d00-44c7-11e8-9c4a-68220b22da0d.png)
几乎没做啥负载就100%了 Nignx始终安装不上，mysql和ftp也启动不了
